version: '3.8'

services:
  lpr-checkpoint-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: HH/lpr-checkpoint-frontend:latest
    container_name: lpr-checkpoint-frontend
    ports:
      - "3001:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  node_modules: {}